name: Build and Run .NET Project

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and Run Project
      run: |
        dotnet restore
        dotnet build
        dotnet run --project CsvParser
