name: Build and Run .NET Project

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy external files
      run: cp $GITHUB_WORKSPACE/CsvParser/Credentials/key.json home/runner/work/ActionTest/ActionTest/CsvParser

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and Run Project
      run: |
        dotnet restore
        dotnet build
        dotnet run --project CsvParser
